site:
  title: OpenCPN Developer Manual
  url: https://opencpn-manuals.github.io/development/
  start_page:  ocpn-dev-manual:ROOT:intro-AboutThisManual.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      edit_url: false

ui:   
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true
