site:
  title: OpenCPN Developer Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:intro-AboutThisManual.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      edit_url: false
ui:   
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll


output:
  dir: ./docs
  clean: true
